language: android
licenses:
  - '.+'
jdk:
  - oraclejdk8

before_install:
  - wget https://services.gradle.org/distributions/gradle-6.6.1-bin.zip
  - unzip -qq gradle-6.6.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.6.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - chmod +x gradlew
  - gradle -v

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-android-17
script:  gradle wrapper --gradle-version 6.6.1 && ./gradlew build